In [1]:
import numpy as np

In [2]:
a=np.array([10,8,5,1])
b=np.array([5,15,9,7])

In [3]:
a+b

array([15, 23, 14,  8])

In [4]:
a-b

array([ 5, -7, -4, -6])

In [5]:
a=np.array([120,45,68])
omega=0.2

omega*a

array([24. ,  9. , 13.6])

In [6]:
x=np.array

In [9]:
t=np.array([2,3,2.5])
exchange_rate=72

t_r=exchange_rate*t
t_r

array([144., 216., 180.])

In [10]:
a=np.array([120,150,90])
w=np.array([130,130,130])

a+w+t_r

array([394., 496., 400.])