In [1]:
import numpy as np

In [3]:
p=np.array([2,4,5])
v=np.array([8,10,2])
s=np.array([0,12,7])

500*p+100*v+0*s

array([1800, 3000, 2700])

In [4]:
x=np.array([4,5])
y=np.array([2,1])
u=np.array([1,0])

2*x+(-3*y)+5*u

array([7, 7])

In [5]:
m=np.array([3,4,5,9])
s=np.array([1,5,3,6])

400*s-200*m

array([-200, 1200,  200,  600])