In [1]:
import numpy as np

In [2]:
X = np.matrix([[1,1],[1,2],[0,-1]])
X

matrix([[ 1,  1],
        [ 1,  2],
        [ 0, -1]])

In [3]:
X.T

matrix([[ 1,  1,  0],
        [ 1,  2, -1]])

In [4]:
X*X.T

matrix([[ 2,  3, -1],
        [ 3,  5, -2],
        [-1, -2,  1]])

In [9]:
A = np.matrix([[1,1],[2,-1],[1,2]])
A

matrix([[ 1,  1],
        [ 2, -1],
        [ 1,  2]])

In [10]:
A * A.T

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])