In [1]:
import numpy as np

In [2]:
A = np.matrix([[1,-5,3],[2,2,1],[0,3,1],[2,4,12]])
A

matrix([[ 1, -5,  3],
        [ 2,  2,  1],
        [ 0,  3,  1],
        [ 2,  4, 12]])

In [3]:
A.shape

(4, 3)

In [4]:
print('A_23=',A[1,2], 'A_32=',A[2,1], 'A_33=',A[2,2])

A_23= 1 A_32= 3 A_33= 1


In [5]:
A = np.matrix("1,-5;2,2;0,3")
v = np.array([7,5,1])

In [6]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [7]:
A.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

In [8]:
v

array([7, 5, 1])

In [9]:
v.T

array([7, 5, 1])

In [12]:
A = np.matrix("1,1;5,7")
B = np.matrix("6,1;-5,5")
C = A + B
C

matrix([[ 7,  2],
        [ 0, 12]])