In [1]:
import numpy as np
import pandas as pd

In [2]:
a=np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [3]:
np.array([1,2,3], dtype='float')

array([1., 2., 3.])

In [4]:
x=[1,2,3]
x_arr=np.array(x)
print(x, type(x))
print(x_arr, type(x_arr))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
np.random.randint(-4, 2, 10)

array([ 1, -1,  0, -4, -3, -1,  0,  1, -1,  1])

In [9]:
data = [65, 70, 120, 35]
s = pd.Series(data)
print('Series:\n', s)

Series:
 0     65
1     70
2    120
3     35
dtype: int64


In [10]:
x = s.values
print('vactor:\n', x)
print('type of x:',type(x))

vactor:
 [ 65  70 120  35]
type of x: <class 'numpy.ndarray'>


In [11]:
d = {'$$': [65,70,120,35], '2.Area': [50,52,80,33], '3.Rooms:': [3,2,1,1], '4.Floor': [5,12,10,3], '5.Demo': [8,4,5,10]}
df = pd.DataFrame(d)
print('Data Frame:\n', df)

Data Frame:
     $$  2.Area  3.Rooms:  4.Floor  5.Demo
0   65      50         3        5       8
1   70      52         2       12       4
2  120      80         1       10       5
3   35      33         1        3      10


In [12]:
A = df.values
print('Matrix:\n', A)

Matrix:
 [[ 65  50   3   5   8]
 [ 70  52   2  12   4]
 [120  80   1  10   5]
 [ 35  33   1   3  10]]


In [13]:
x=A[1]
print('Second apartment vector:\n',x)
print('type of x:',type(x))

Second apartment vector:
 [70 52  2 12  4]
type of x: <class 'numpy.ndarray'>


In [14]:
y=A[:,0]
print('$$ vector:\n',y)

$$ vector:
 [ 65  70 120  35]


In [15]:
print('$$ of 3 apartment:',y[2])

$$ of 3 apartment: 120


In [16]:
print('Number of apartments = diim(x):',len(x))

Number of apartments = diim(x): 5


In [17]:
a=np.array([1,2,3])
b=np.array([6,7,8])
print('a+b:', a+b)
print('2a:', 2*a)

a+b: [ 7  9 11]
2a: [2 4 6]


In [18]:
a_list=[1,2,3]
b_list=[6,7,8]
print('a+b:', a_list+a_list)
print('2a:', 2*a_list)

a+b: [1, 2, 3, 1, 2, 3]
2a: [1, 2, 3, 1, 2, 3]


In [19]:
a=np.array([1,2,3])
b=np.array([6,7,8])
c=np.array([1,0,1])

d=2*a+2*b+3*c
print('linear combination:', d)

linear combination: [17 18 25]


In [20]:
s=np.dot(a,b)
print('scalar product:', s)
print('coordinate product:', a*b)

scalar product: 44
coordinate product: [ 6 14 24]


In [21]:
s1=a@b
print('scalar product:', s1)

scalar product: 44


In [22]:
l=np.linalg.norm(a)
print('length of a:', l)

length of a: 3.7416573867739413


In [23]:
a_norm=a/np.linalg.norm(a)
print('a_norm:', a_norm)
print('length of a_norm:', np.linalg.norm(a_norm))

a_norm: [0.26726124 0.53452248 0.80178373]
length of a_norm: 1.0


In [24]:
a=np.array([1,2,1])
b=a*2
c=np.array([-1,1,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 2 1]
b: [2 4 2]
c: [-1  1 -1]


In [26]:
print('(a,b):',np.dot(a,b))
print('(a,c):',np.dot(a,c))
print('(b,c):',np.dot(b,c))

(a,b): 12
(a,c): 0
(b,c): 0


In [27]:
a=np.array([1,0,1])
b=np.array([0,1,0])
c=np.array([1,0,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 0 1]
b: [0 1 0]
c: [ 1  0 -1]


In [28]:
print('(a,b):',np.dot(a,b))
print('(a,c):',np.dot(a,c))
print('(b,c):',np.dot(b,c))

(a,b): 0
(a,c): 0
(b,c): 0


In [30]:
c1=np.array([1,0,4])
print('a:',a)
print('b:',b)
print('c1:',c1)

a: [1 0 1]
b: [0 1 0]
c1: [1 0 4]


In [32]:
print('(a,b):',a@b)
print('(a,c):',a@c1)
print('(b,c):',b@c1)

(a,b): 0
(a,c): 5
(b,c): 0
