In [26]:
# 1.15. --> Практика. Умножение матриц

import numpy as np
import pandas as pd

In [7]:
# task 1

A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [8]:
# 1.15.1

A@x

array([26, 30])

In [9]:
# task 2

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [11]:
# 1.15.2

B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [22]:
# task 3

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [24]:
# 1.15.3

A = np.array([x, y, z]).T
print(A.T@A)

[[22  3  0]
 [ 3  7  0]
 [ 0  0  3]]


In [30]:
# tqssk 4

Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [47]:
# 1.15.4

count_b = np.array(Count_DF.values[1])
price_b = np.array(Price_DF.values[1])

count_b*price_b

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [66]:
# 1.15.5

C = np.array(Count_DF.values)
P = np.array(Price_DF.values)
com = [0.2, 0.2, 0.3, 0.1, 0.1]

salon_inc = (P*C)@(com)

print(salon_inc)




[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [67]:
# 1.15.6

C = np.array(Count_DF.values)
P = np.array(Price_DF.values)
com = [0.2, 0.2, 0.3, 0.1, 0.1]

styl_inc = (P*C)@(np.ones(5)-com)

print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]
