In [1]:
import numpy as np
import pandas as pd

In [4]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
print(Hut_Paradise_DF)

   1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40


In [5]:
hp = Hut_Paradise_DF.values
print(hp)

[[ 65  50   3   5   8  37]
 [ 70  52   2  12   4  40]
 [120  80   1  10   5  65]
 [ 35  33   1   3  10  20]
 [ 40  33   1   6  20  16]
 [ 50  44   2  13  12  35]
 [100  80   4   8   5  60]
 [ 90  65   3  21   1  50]
 [ 85  65   2   5  10  40]]


In [16]:
# 1.7.1
print(hp[4])

[40 33  1  6 20 16]


In [14]:
#1.7.2
print(hp[:,3])

[ 5 12 10  3  6 13  8 21  5]


In [8]:
#1.7.3
print(hp[2,3])

10


In [9]:
#1.7.4
print(len(hp[:,0]))

9


In [17]:
#1.7.5
total_area = np.array(hp[:,1])
inhabited_area = np.array(hp[:,5])
uninhabited_area = total_area - inhabited_area
print(uninhabited_area)

[13 12 15 13 17  9 20 15 25]


In [18]:
#1.7.6
rub = hp[:,0]
uah = 0.4*rub
print(uah)

[26. 28. 48. 14. 16. 20. 40. 36. 34.]


In [19]:
#1.7.7
dur = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
demo = np.array(hp[:,4])
demo_d = dur@demo
print(demo_d)

1348


In [20]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [22]:
#1.7.8
r = v*2+w*-3
print(r)

[-3 14  3  4  2]


In [24]:
#1.7.9
r@u

0

In [25]:
#1.7.10
u_norm = u/np.linalg.norm(u)
v_norm = v/np.linalg.norm(v)
w_norm = w/np.linalg.norm(w)
print('u_norm:', u_norm)
print('v_norm:', v_norm)
print('w_norm:', w_norm)

u_norm: [0.8660254  0.         0.28867513 0.28867513 0.28867513]
v_norm: [ 0.          0.33333333  0.          0.66666667 -0.66666667]
w_norm: [ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]
