In [83]:
import numpy as np

In [84]:
arr1 = np.array([1,2,3,4])

In [85]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [86]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr3)

(3, 3)

In [87]:
import pandas as pd

df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [88]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [89]:
np.empty(5)

array([14., 10.,  6., 56., 40.])

In [90]:
np.zeros((10, 7)) 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [91]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [92]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [94]:
np.arange(0, 21, 7)

array([ 0,  7, 14])

In [95]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [96]:
np.random.randint(0, 10, (3, 3))

array([[1, 4, 2],
       [6, 1, 9],
       [2, 0, 2]])

In [97]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [98]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [99]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [100]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [101]:
np.random.randint(0, 4, (3, 3))

array([[0, 3, 0],
       [2, 2, 3],
       [3, 2, 1]])

In [102]:
np.random.randint(0, 5, 3)

array([0, 1, 4])

In [103]:
np.ones((4, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [104]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [105]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [106]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [107]:
my_array = np.array([x for x in range(10)])
my_array[5]

5

In [108]:
my_array[-1]

9

In [109]:
my_array[3:6]

array([3, 4, 5])

In [110]:
my_array[1:8:3]

array([1, 4, 7])

In [111]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[1][2]

12

In [112]:
my_array[1,2]

12

In [113]:
my_array[1]

array([10, 11, 12, 13])

In [114]:
my_array[:,2]

array([ 3, 12, 47])

In [115]:
my_array[1:,1:3]

array([[11, 12],
       [46, 47]])

In [116]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [117]:
x = 0
for i in range(len(big_secret)):
    x += big_secret[i,-1]
    
round(x, 2)

3154.33

In [118]:
x = 0
new_secret = big_secret[:,0:5]
for i in range(len(new_secret)):
    x+=new_secret[i,i]
    
round(x, 2)

121.37

In [119]:
x = 1
new_secret = big_secret[:,-5:]
for i in range(len(new_secret)):
    x*=new_secret[i,i]
 
round(x, 2)

341505315559.23

In [120]:
my_array = np.random.randint(1, 100, (4, 6))
my_array

array([[64, 49, 18, 99, 41, 73],
       [83, 85, 29, 61, 50, 22],
       [22, 79, 42, 38, 55, 31],
       [57, 23, 16, 17, 55, 47]])

In [121]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[29, 61],
       [42, 38]])

In [122]:
my_slice[:] = 0
my_array

array([[64, 49, 18, 99, 41, 73],
       [83, 85,  0,  0, 50, 22],
       [22, 79,  0,  0, 55, 31],
       [57, 23, 16, 17, 55, 47]])

In [127]:
for i in range(len(big_secret)):
    for j in range(len(big_secret[i])):
        if i%2==0 and j%2==0:
            big_secret[i, j] = -1
        elif i%2!=0 and j%2!=0:
            big_secret[i, j] = 1
            
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

In [128]:
x = 0
new_secret = big_secret[:,0:5]
for i in range(len(new_secret)):
    x+=new_secret[i,i]
    
x

-1.0

In [129]:
x = 1
new_secret = big_secret[:,-5:]
for i in range(len(new_secret)):
    x*=new_secret[i,i]
 
x

-1.0